version: '3.8'
name: itenium-socks

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    networks:
      - socks-n-smells
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - PGPORT=5433
      - POSTGRES_DB=socks 
    ports:
      - 5433:5433
    volumes:
      - postgres-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  socks-n-smells:
    name: socks-n-smells
